### ISSUE TITLE
Message Provider Validation against Pact Broker Wrongly Succeeds

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/pact-node#134]
I have a strange behavior during message provider verification.

I successfully published a message pact to my test pact broker instance (v 2.26.0, hosted by you, if it helps ;)). When viewing the message pact in the pact broker, it says `Note: this contract could not be parsed to a v1 or v2 Pact, showing raw content instead.` and only shows the JSON.

When I run my [provider test](https://github.com/thombergs/code-examples/blob/master/pact/pact-node-messages/src/provider/hero-event-producer.spec.js), **it succeeds, even though my [message provider](https://github.com/thombergs/code-examples/blob/master/pact/pact-node-messages/src/provider/hero-event-producer.js) returns an invalid message**.

**When I run the provider test against a local pact file instead, it fails, as I would expect.**

Maybe the verifier doesn't find the pact on the broker (because the broker does not support message contracts) and since it hasn't found a pact, it just succeeds? If this is the case:
* I would expect the verifier to fail if it doesn't find any pacts to test against.
* when will the pact broker support message contracts? ;)

**Comment by mefellows** [comment]
I think this issue is resolved now @thombergs - can you please confirm?

**Comment by ltwyda** [comment]
Hi @mefellows, @thombergs,

I am using a pact broker locally via "pactfoundation/pact-broker:latest" docker image to trial the broker as I am using the folder/repository alternative approach to maintain pacts currently as proof of concept.

I'm trying to view a pact v3 definition that I have created for domain events in the Pact broker but the broker UI says - "this contract could not be parsed to a v1 or v2 Pact, showing raw content instead". The pact definition uses some matchers.

Is it supposed to work with the latest version of pact broker and pact v3 definition? Is there any workaround to prettify the doc instead of rendering the raw pact definition in broker UI?

Thanks

**Comment by mefellows** [comment]
@ltwyda this question is off topic for the issue, however the answer is simple: the OSS pact broker doesn't display v3/v4 pacts at the moment. There is an open issue on that repository, and I'm sure a PR would be accepted to improve the rendering.
