### ISSUE TITLE
Unable to run canDeploy using latest

### ISSUE THREAD

**Issue by rafael-anachoreta** [pact-foundation/pact-node#141]
## Software versions

-   **OS**: Mac OSX 10.14.3
-   **Library version**: 6.21.3
-   **Node Version**: v10.15.1

## Expected behaviour
When using `latest:[pacticipant]` I expected the can-I-deploy check to run for the latest version of the pacticipant.

## Actual behaviour
Script ends execution with:
```bash
TypeError: Must provide the same number of pacticipant and version
```

## Steps to reproduce
```javascript
const pact = require("@pact-foundation/pact-node");

const checkProvider = {
  pactBroker: "http://localhost",
  pacticipant: ["service"],
  latest: ["f53101e8"], //tried true, "", "master", "service"
};

pact.canDeploy(checkProvider)
```

And if I add the pacticipant version to the mix I get ```Error: A version number and latest flag cannot both be specified for service```

**Comment by TimothyJones** [comment]
Thanks for the report, and sorry about this. Looks to be a bug.

For now, you should be able to work around it by using `pacticipantVersion` instead of `latest`:

```
const checkProvider = {
  pactBroker: "http://localhost",
  pacticipant: ["service"],
  pacticipantVersion: ["f53101e8"],
};
```

Let us know if that helps, and I'll see if I can get some time to look into the bug next week.

**Comment by mboudreau** [comment]
@rafael-anachoreta hm, this will be a bit more difficult than I imagined.  I tried my hand at it, but because the low level binary has the concept of order aware arguments, it's making it particularly hard to abstract out the functionality.  

I've created an issue for pact-broker to use the single responsibility principle which should make this much easier to work with.  When that goes through, this should be fixed easily enough.

Cheers.

**Comment by TimothyJones** [comment]
I think we could get some milage through changing the options API for `canDeploy`- 

```
const checkProvider = {
  pactBroker: "http://localhost",
  pacticipant: ["service1","service2"],
  pacticipantVersion: [{ tag: "TAG1", latest: true },{version: "VERSION2"}],
};
```

This would be more difficult for the node CLI, but if we replaced the node CLI with binstubs as in [this issue](https://github.com/pact-foundation/pact-node/issues/83), then we could sidestep that problem (and have less code to maintain). Thoughts?

**Comment by rafael-anachoreta** [comment]
Thanks all for looking into it, you are awesome! 🥇 
I really like @TimothyJones's suggestion and initially thought this was how it was meant to be used.
> ```
> const checkProvider = {
>   pactBroker: "http://localhost",
>   pacticipant: ["service1","service2"],
>   pacticipantVersion: [{ tag: "TAG1", latest: true },{version: "VERSION2"}],
> };
> ```

I don't necessarily think the exposed API has to be 1-to-1 copy of the CLI. In other words, I think it is fine to have `canDeploy` take more intuitive options and then do some magic to convert that into something the CLI can understand. 🙂 

👍 from a user perspective.

**Comment by mboudreau** [comment]
@rafael-anachoreta Hey, I released a new version of pact-node, 7.0.0, which includes fixes for 'latest' and 'to' parameters.  Please go ahead and try it out.  It's a major version because it had to break the existing API of being able to do multiple participants/versions in one go, but I found this to be overly confusing and unnecessary.

Let me know how you go :)

**Comment by TimothyJones** [comment]
> break the existing API of being able to do multiple participants/versions in one go,

I think this is an important feature that we should support. Without it, users would have to call `canDeploy` in a loop for some use cases - eg where you know a deployment needs to talk to multiple versions of a consumer (like deploying a provider that is consumed by multiple versions of a mobile app).

If there are no objections, I'd like to take a crack at a PR to fix this up.

Syncing the internal API with `pact-cli.js` might be a challenge, but I think that might be better served by doing #83, instead of writing the converting code between the paradigms of `pact-cli.js` and the broker cli. I started on a PR for that today.

**Comment by mboudreau** [comment]
@TimothyJones we could create binstubs, but the issue here is that ruby takes a long time to run and I wanted to have better validation and user experience on the CLI side.  I also thought of using Node as an abstraction for the underlying CLI so that the underlying binaries can change and break, but the node API wouldn't need to.

It was also a way to abstract out some ruby conventions which are non-standard in the industry and use better naming conventions for parameters.  In the end, it's all about enhancing the developer experience which I feel is sometimes lacking with the straight binaries.
