### ISSUE TITLE
standalone extract owner groups

### ISSUE THREAD

**Issue by qamatic** [pact-foundation/pact-node#166]
## Software versions

"@pact-foundation/pact-node": "8.2.0"

## Expected behaviour

tar extracting should happen with current logged in user / group

## Actual behaviour

tar which extracts files but doing with archieve file owner groups  which prevents executes files  unless you do chown to current user.

## Steps to reproduce

just create a dockerfile
 FROM node:10.15.3-alpine AS build
try npm install /@pact-foundation/pact-node

and you could see standalone files in node_modules/@pact-foundation/pact-node having 2000 as owner group ids.

**Comment by senips1001** [comment]
here is the work around if anyone wants .  Add this in your Dockerfile
RUN chown -R root:root node_modules/@pact-foundation/pact-node/standalone/

**Comment by senips1001** [comment]
I also ran into several other problems.  So the  shell scripts written in mix of sh and bash under standalone pact distribution so no good if your docker uses ash/sh shells.  I am logging here if the team would like to investigate and fix it future.

**Comment by mefellows** [comment]
Thanks @senips1001. We know we have a dependency on bash at the moment - you'll find more on this over on the pact-js repo (as well as a number of others). Appreciate the visibility here is difficult, and we'd like to move to our docs.pact.io website for all to see.

I'm not convinced of the underlying permissions issue - would you be willing to share a code example that reproduces it?

**Comment by senips** [comment]
Well, I was literally on this about 3days to run the whole thing run finally.  Anyway here is an example https://github.com/qamatic/examples-pact

**Comment by TimothyJones** [comment]
Thanks for the example repo!

According to the documentation of [`tar`](https://www.npmjs.com/package/tar), the default way it handles permissions changes depending on whether or not it is run as root: 

> `preserveOwner` If true, tar will set the uid and gid of extracted entries to the uid and gid fields in the archive. This defaults to true when run as root, and false otherwise. If false, then files and directories will be set with the owner and group of the user running the process. 

This is not what we want, and I expect it affects docker users the most (as they're most likely to run as root). 

I think we should correct this, because extracting with the owners stored in the archive is definitely not correct. 

However, the permissions that it extracts with are `rwxr-xr-x`, so I think it shouldn't prevent execution of the binaries. I was able to executes the binaries in the example docker container:

```
  "scripts": {
    "test": "pact verify -b localhost -u http://localhost"
  },
```

This fails with `/bin/sh: ./standalone/linux-x64-1.64.1/bin/pact-provider-verifier: not found` because bash is missing, but results from executing the binary.

We should still fix it though.

**Comment by senips** [comment]
@TimothyJones Thank you for the fix.
