### ISSUE TITLE
It would be nice to mention that the stub server also needs to be started

### ISSUE THREAD

**Issue by HunorMarton** [pact-foundation/pact-node#201]
I have to say I didn't thoroughly read the documentation, but it would be really nice if instead of this:
```
var pact = require('@pact-foundation/pact-node');
var server = pact.createStub({
	...
});
```
it would be like this:
```
var pact = require('@pact-foundation/pact-node');
var server = pact.createStub({
	...
});
server.start().then(function() {
	// Do something after it started
});
```

**Comment by TimothyJones** [comment]
This is present in the documentation here: https://github.com/pact-foundation/pact-node#start-a-mock-server

I don't think the initial example should immediately start the server, because it's possible that the user might want to [configure server events](https://github.com/pact-foundation/pact-node#mock-server-events) first.

If you didn't read the documentation closely, you might have missed that this package isn't intended to be used directly, unless you're working on your own wrapper for Pact. You might want to check out https://github.com/pact-foundation/pact-js , which starts and stops the mock for you.
