### ISSUE TITLE
Allow 'format' to be specified when calling pact-ruby-standalone

### ISSUE THREAD

**Issue by joshhendo** [pact-foundation/pact-node#84]
In my provider project, I'm interested in presenting the results in a different format (e.g. having multiple mocha tests for each thing tested, rather than a large single test).

Taking a look at how I could parse the output from `verifyProvider`, I noticed that the underlying binary (`pact-ruby-standalone`) allows a `--format` flag to be passed, with JSON available as one of the outputs.

I have quickly put together a proof of concept here: https://github.com/pact-foundation/pact-node/pull/86 . By not appending the `stderr` output to the string (due to it adding `INFO` lines), and by specifying the format to be `json`, I was able to parse the JSON response.

I'd be happy to work on implementing this feature fully beyond the proof of concept (e.g. agree on what the options should be called, adding in tests etc.)

**Comment by mboudreau** [comment]
Closing this as it's been pushed out with version 6.18.0.

**Comment by mboudreau** [comment]
@joshhendo I'm going to do another release (6.18.1) that instead of using "RspecJunitFormatter" for format, just uses "xml" instead, so the option is either "json" or "xml".  I feel like the abstraction is needed and better reflects what the binary is actually doing.  Hope that's alright.

New version going out now.
